### ISSUE TITLE
[깃 정책변경] dev에 merge시 PR필수, 모든 팀원(2명) 승인 필수

### ISSUE THREAD

**Issue by gogoheejun** [99-final-project/back-end#5]
previous 정책에서는 각 브랜치에서 큰 기능이 완료되어서 한번에 dev에 PR을 했습니다.

**new 정책**에서는 **작은 기능단위**로 dev에 PR을 하며, 그 때마다 **코드리뷰**를 하여 댓글을 달고, 모든 팀원이 **approval**을 해야 merge가 가능하도록 설정을 바꾸었습니다.

**Comment by NayoungBae** [comment]
확인했습니다!

**Comment by gogoheejun** [comment]
PR시 형식은 다음과 같습니다!

제목형식 : 
ex)
[기능추가] 댓글 좋아요 기능

처럼 하시면 됩니다.

내용형식:

ex)
- 구체 내용1
- 구체 내용2
그리고 하고 싶은 말(pr했어요~~~재밌어용~~~ㅎㅎ)

 글구 코드리뷰하며 코멘트를 다실 때에는 이모티콘 해주기ㅋㅋㅋ😆

**Comment by jhhong0930** [comment]
확인 했슴다
